/*
 * Gatewerk SQL migration apply pipeline (M0).
 *
 * Runs as a one-shot init container before gatewerk-api starts. Reads SQL
 * files from packages/db/migrations/ in lexical order, tracks applied state
 * in `schema_migrations`, and applies any unapplied files via postgres.js.
 *
 * Background:
 *   v1.3 Round 3 deploy verification uncovered that migrations 021 + 022
 *   shipped to prod code-only — the schema never followed because the
 *   compose-up flow had no migration step. Timeout worker crashlooped on
 *   `assignment_ladder does not exist` for ~2 days. M0 closes that gap.
 *
 * Three intentional design choices worth documenting here:
 *
 * 1. STANDALONE — no import from packages/db/src. The drizzle schema and the
 *    raw SQL files can drift; this script is the authority on what the SQL
 *    actually says. Less surface = fewer ways for the migration tool itself
 *    to break.
 *
 * 2. ADVISORY LOCK 7423842 — a pg session-level advisory lock around the
 *    entire run prevents two parallel containers from racing each other
 *    during a coordinated redeploy. The constant is arbitrary but fixed:
 *    "GATEWERK".charCodeAt sum is 754 — picked 7423842 instead because the
 *    leading 742 reads as "GW" via that mapping and the suffix is recognisable
 *    in pg_locks output. Don't change it without coordinating prod cutover.
 *
 * 3. AUTO-BACKFILL ON ESTABLISHED DB — first M0 deploy must NOT re-run the
 *    24+ migrations that prod has already applied. Decision rule:
 *      - schema_migrations does not exist + `templates` table exists
 *        → established prod DB; insert all known migration ids and exit 0.
 *      - schema_migrations does not exist + `templates` does not exist
 *        → truly fresh DB; apply baseline.sql (generated by drizzle-kit export)
 *          to materialise the full schema up to the `baseline-through` marker id,
 *          mark only corpus ids lexicographically <= the marker as applied, then
 *          fall through to the normal apply loop so any ids > marker are applied
 *          immediately. This unblocks `git clone → docker compose up` installs.
 *      - schema_migrations exists → normal apply-unapplied-only path.
 *    `templates` is the sentinel because it landed in the very first
 *    drizzle-kit push and is never absent from a populated Gatewerk DB.
 *
 * 4. BASELINE.SQL — committed at packages/db/scripts/baseline.sql, generated
 *    by `pnpm --filter @gatewerk/db exec drizzle-kit export --sql`. The first
 *    line MUST be `-- baseline-through: <last-migration-id-covered>` (e.g.
 *    `073_template_fields_snapshot`). The fresh-DB branch reads this marker and
 *    marks ONLY corpus ids <= the marker as applied; any newer ids fall through
 *    to the normal apply loop and are executed as real migrations.
 *    When regenerating (after new schema additions), update the marker line to
 *    the new corpus max so the boundary advances correctly.
 */

import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import postgres from "postgres";

const ADVISORY_LOCK_KEY = 7423842;
const SENTINEL_TABLE = "templates";

const SCRIPTS_DIR = dirname(fileURLToPath(import.meta.url));

const DEFAULT_MIGRATIONS_DIR = join(SCRIPTS_DIR, "..", "migrations");

const DEFAULT_BASELINE_SQL = join(SCRIPTS_DIR, "baseline.sql");

export interface MigrateOptions {
  databaseUrl: string;
  migrationsDir?: string;
  /** Path to baseline.sql applied on truly fresh databases. Defaults to the
   *  committed packages/db/scripts/baseline.sql. Tests may pass a custom path. */
  baselineSqlPath?: string;
  log?: (msg: string) => void;
}

export interface MigrateResult {
  applied: string[];
  skipped: string[];
  backfilled: string[];
}

export async function runMigrations(
  opts: MigrateOptions,
): Promise<MigrateResult> {
  const log = opts.log ?? ((msg: string) => console.log(msg));
  const migrationsDir = opts.migrationsDir ?? DEFAULT_MIGRATIONS_DIR;
  const baselineSqlPath = opts.baselineSqlPath ?? DEFAULT_BASELINE_SQL;

  // max:1 keeps everything on one connection so the advisory lock and the
  // session it was acquired on stay paired across statements.
  const sql = postgres(opts.databaseUrl, {
    max: 1,
    onnotice: () => {},
    prepare: false,
  });

  let lockHeld = false;
  try {
    await sql`SELECT pg_advisory_lock(${ADVISORY_LOCK_KEY})`;
    lockHeld = true;

    const allIds = listMigrationIds(migrationsDir);

    const migrationsTableExists = await regclassExists(sql, "schema_migrations");
    const sentinelExists = await regclassExists(sql, SENTINEL_TABLE);

    await sql`
      CREATE TABLE IF NOT EXISTS schema_migrations (
        id text PRIMARY KEY,
        applied_at timestamptz NOT NULL DEFAULT NOW()
      )
    `;

    if (!migrationsTableExists && sentinelExists) {
      // Established prod DB that predates the M0 migration pipeline.
      // `templates` exists but schema_migrations doesn't — backfill ids only.
      log(
        `[migrate] Detected established DB (${SENTINEL_TABLE} present, schema_migrations absent); ` +
          `backfilling ${allIds.length} migrations as already-applied`,
      );
      for (const id of allIds) {
        await sql`
          INSERT INTO schema_migrations (id) VALUES (${id})
          ON CONFLICT (id) DO NOTHING
        `;
      }
      log(`[migrate] Backfill complete — applied=0 backfilled=${allIds.length}`);
      return { applied: [], skipped: [], backfilled: allIds };
    }

    if (!migrationsTableExists && !sentinelExists) {
      // Truly fresh database — schema_migrations absent AND templates absent.
      // The migration corpus cannot bootstrap an empty DB (migration 001 ALTERs
      // `reviews`, which no migration creates). Apply baseline.sql to materialise
      // the full schema up through the `baseline-through` marker, mark only ids
      // <= the marker as applied, then fall through to the normal apply loop so
      // any corpus ids added after the baseline was generated are applied as real
      // migrations. Never return early here — forward-drift ids must not be
      // silently swallowed.
      //
      // Regeneration rule: when adding new migrations, regenerate baseline.sql
      // with `drizzle-kit export --sql` and update its `baseline-through` marker
      // to the new corpus max so the boundary advances.
      const baselineSql = readFileSync(baselineSqlPath, "utf8");
      const markerMatch = baselineSql.match(
        /^--\s*baseline-through:\s*(\S+)/m,
      );
      if (!markerMatch) {
        throw new Error(
          `[migrate] baseline.sql is missing required header line ` +
            `"-- baseline-through: <last-migration-id>" (path: ${baselineSqlPath})`,
        );
      }
      const baselineThrough = markerMatch[1];
      log(
        `[migrate] bootstrap: fresh DB detected — applying baseline.sql through ${baselineThrough}`,
      );
      await sql.unsafe(baselineSql);
      const baselineIds = allIds.filter((id) => id <= baselineThrough);
      for (const id of baselineIds) {
        await sql`
          INSERT INTO schema_migrations (id) VALUES (${id})
          ON CONFLICT (id) DO NOTHING
        `;
      }
      log(
        `[migrate] bootstrap: baseline applied — ${baselineIds.length} migrations marked (through ${baselineThrough}); ` +
          `${allIds.length - baselineIds.length} newer id(s) will be applied below`,
      );
      // Fall through — do NOT return. The normal apply loop below will apply
      // any corpus ids that sort after baselineThrough.
    }

    const appliedRows = await sql<{ id: string }[]>`
      SELECT id FROM schema_migrations
    `;
    const alreadyApplied = new Set(appliedRows.map((r) => r.id));

    const applied: string[] = [];
    const skipped: string[] = [];

    for (const id of allIds) {
      if (alreadyApplied.has(id)) {
        log(`[migrate] SKIP  ${id}`);
        skipped.push(id);
        continue;
      }
      const sqlText = readFileSync(join(migrationsDir, `${id}.sql`), "utf8");

      if (containsConcurrentIndex(sqlText)) {
        // CONCURRENTLY path. Postgres forbids `CREATE INDEX CONCURRENTLY`
        // inside an explicit transaction, so these migrations apply via
        // simple-query protocol (auto-commit per statement) and the
        // schema_migrations INSERT lands afterwards. The tradeoff: if a
        // CONCURRENTLY statement fails partway, individual index creates may
        // be partially applied (Postgres marks failed CONCURRENTLY indexes
        // as INVALID). Re-running the migration is safe — every CONCURRENTLY
        // usage in our corpus is `IF NOT EXISTS` and INVALID indexes get
        // rebuilt. Affected ids in the current corpus: 015, 016, 021, 022.
        await sql.unsafe(sqlText);
        await sql`INSERT INTO schema_migrations (id) VALUES (${id})`;
      } else {
        // non-CONCURRENTLY path. Wrap the whole migration + the
        // schema_migrations INSERT in a single postgres.js transaction so a
        // partial failure rolls back cleanly, rather than leaving some
        // statements applied with no schema_migrations row to reconcile by
        // hand.
        //
        // We use `tx.unsafe(text, params)` for both the migration and the
        // marker INSERT because postgres.js's `TransactionSql` type uses
        // `Omit<Sql, ...>` which strips the template-tag call signature in
        // TypeScript. `unsafe()` with a parameter array is the parameterised
        // path (no string interpolation of `id`), so we keep injection
        // protection on the marker INSERT.
        await sql.begin(async (tx) => {
          await tx.unsafe(sqlText);
          await tx.unsafe(
            "INSERT INTO schema_migrations (id) VALUES ($1)",
            [id],
          );
        });
      }

      log(`[migrate] APPLY ${id}`);
      applied.push(id);
    }

    log(
      `[migrate] Done — applied=${applied.length} skipped=${skipped.length} backfilled=0`,
    );
    return { applied, skipped, backfilled: [] };
  } finally {
    if (lockHeld) {
      try {
        await sql`SELECT pg_advisory_unlock(${ADVISORY_LOCK_KEY})`;
      } catch {
        // Connection may already be poisoned; the lock releases on session end anyway.
      }
    }
    await sql.end({ timeout: 5 });
  }
}

function listMigrationIds(dir: string): string[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith(".sql"))
    .sort()
    .map((f) => f.replace(/\.sql$/, ""));
}

/**
 * Pure SQL-text inspector. Returns true iff the SQL
 * text contains a `CREATE INDEX CONCURRENTLY` (or `CREATE UNIQUE INDEX
 * CONCURRENTLY`) statement. Migrations that match cannot run inside an
 * explicit transaction; the apply loop uses simple-query protocol for those
 * and `sql.begin()` for everything else.
 *
 * Exported so unit tests can pin the detection logic without spinning up
 * Postgres. Match is case-insensitive and tolerant of any whitespace between
 * the keywords. Comment-stripping is intentionally not done — the regex is
 * scoped tightly enough that a SQL string literal containing this exact
 * keyword phrase would be a bizarre coincidence, and false positives only
 * cost us the transaction wrap (correctness-equivalent, just no rollback).
 */
export function containsConcurrentIndex(sqlText: string): boolean {
  return /CREATE\s+(?:UNIQUE\s+)?INDEX\s+CONCURRENTLY/i.test(sqlText);
}

async function regclassExists(
  sql: postgres.Sql,
  table: string,
): Promise<boolean> {
  const rows = await sql<{ exists: string | null }[]>`
    SELECT to_regclass(${"public." + table})::text AS exists
  `;
  return rows[0]?.exists != null;
}

async function main(): Promise<void> {
  const url = process.env.DATABASE_URL;
  if (!url) {
    console.error("[migrate] DATABASE_URL is not set; refusing to run.");
    process.exit(1);
  }
  try {
    await runMigrations({ databaseUrl: url });
    process.exit(0);
  } catch (err) {
    console.error("[migrate] FAILED:", err);
    process.exit(1);
  }
}

// Run as CLI when invoked directly. Detects both Bun (`import.meta.main`)
// and Node (`process.argv[1]` matches this file) so the same script works
// in production (Bun via Dockerfile.api) and in dev (`node`/`tsx`).
const importMeta = import.meta as ImportMeta & { main?: boolean };
const isMainModule =
  importMeta.main === true ||
  (process.argv[1] != null &&
    fileURLToPath(import.meta.url) === process.argv[1]);

if (isMainModule) {
  void main();
}
